import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  es: {
    sidebar: {
      dashboard: 'Dashboard',
      revenue: 'Retorno y Finanzas',
      leads: 'Prospectos',
      campaigns: 'Campañas Meta',
      socialAnalyzer: 'Analizador Social',
      googleIntelligence: 'Google Intelligence',
      admin: 'Administración',
      settings: 'Configuración',
      logout: 'Cerrar Sesión',
      brandTitle: 'ANIMA MKT CRM',
      brandSubtitle: 'Revenue Intelligence',
      closeMenu: 'Cerrar menú',
      mainNavigation: 'Navegación principal',
    },
    header: {
      systemOperating: 'Sistema Operativo',
      secureSession: 'Sesión Segura',
      logout: 'Cerrar Sesión',
      openMenu: 'Abrir menú de navegación',
      logoutTitle: 'Cerrar sesión en Anima MKT CRM',
    },
    roles: {
      super_admin: 'SUPER ADMINISTRADOR',
      admin: 'ADMINISTRADOR',
      client: 'CLIENTE',
      salesperson: 'VENDEDOR',
      media_buyer: 'MEDIA BUYER',
      user: 'USUARIO',
    },
    common: {
      actions: 'Acciones',
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      create: 'Crear',
      add: 'Agregar',
      status: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo',
      suspended: 'Suspendido',
      invited: 'Invitado',
      search: 'Buscar...',
      all: 'Todos',
      retry: 'Reintentar',
      loading: 'Cargando...',
      error: 'Ocurrió un error',
      success: 'Operación exitosa',
      company: 'Empresa',
      selectCompany: 'Seleccione una Empresa',
      allCompanies: 'Todas las Empresas',
      role: 'Rol',
      date: 'Fecha',
      value: 'Valor',
      none: 'Ninguno',
      back: 'Volver',
      confirm: 'Confirmar',
      warning: 'Advertencia',
      exportCsv: 'Exportar CSV',
      exportPdf: 'Exportar PDF',
      from: 'Desde:',
      to: 'Hasta:',
      reset: 'Restablecer',
      allCurrencies: 'Todas las divisas',
      allStages: 'Todas las Etapas',
      allSalespeople: 'Todos los Vendedores',
      allCampaigns: 'Todas las Campañas',
      unassigned: 'Sin asignar',
    },
    dashboard: {
      title: 'Panel de Control & Rendimiento Comercial',
      welcome: 'Bienvenido,',
      leadsCount: 'Prospectos Totales',
      wonLeads: 'Ventas Cerradas',
      conversionRate: 'Tasa de Conversión',
      totalCollected: 'Total Cobrado',
      recentLeads: 'Prospectos Recientes',
      name: 'Nombre',
      email: 'Correo',
      phone: 'Teléfono',
      assignedTo: 'Asignado a',
      leadsInPipeline: 'Leads en Pipeline',
      won: 'Ganados:',
      convRate: 'Tasa Conv.:',
      noData: 'Sin datos',
      collectedRevenue: 'Ingresos Cobrados',
      loadingCurrencies: 'Cargando monedas...',
      errorLoadingCollections: 'Error al cargar cobros',
      noCollections: 'Sin cobros registrados',
      metaInvestment: 'Inversión Meta Ads',
      noMetaData: 'Sin datos de Meta',
      roasOnCollections: 'ROAS sobre Cobros',
      roasCalculated: 'Calculado sobre ingresos cobrados',
      roasRequires: 'Requiere inversión e ingresos',
      pipelineDistribution: 'Distribución del Pipeline',
      loadingDistribution: 'Cargando distribución...',
      errorDistribution: 'No se pudo cargar el desglose.',
      stageNew: '1. Nuevos',
      stageContacted: '2. Contactados',
      stageQualified: '3. Calificados',
      stageWon: '4. Ganados / Cerrados',
      stageLost: '5. Perdidos',
      salespersonPerformance: 'Rendimiento por Vendedor',
      loadingSalespeople: 'Cargando vendedores...',
      errorSalespeople: 'No se pudo cargar el rendimiento por vendedor.',
      noSalespeopleData: 'Sin datos de vendedores para mostrar en este filtro.',
      thSalesperson: 'Vendedor',
      thAssignedLeads: 'Leads Asignados',
      thWon: 'Ganados',
      thSales: 'Ventas',
      thConvRate: 'Tasa Conv.',
      thCollected: 'Cobrado',
      pendingActivation: 'Pendiente activación',
      openPipeline: 'Abrir Pipeline',
      openCampaigns: 'Abrir Campañas',
      pipelineAndAssignments: 'Pipeline & Asignaciones',
      pipelineDesc: 'Tablero Kanban con 5 etapas comerciales, reasignación controlada e importación masiva CSV.',
      salesAndCollections: 'Ventas & Cobros en Centavos',
      salesDesc: 'Control de montos cobrados parciales y totales por divisa con validación de límites.',
      nextStep: 'Próximo Paso: Etapa 4',
      errorUnauthorized: 'Sesión no válida o expirada. Por favor, vuelva a iniciar sesión.',
      errorForbidden: 'No tenés permisos para visualizar las estadísticas de esta empresa.',
      errorNotFound: 'La empresa seleccionada no existe o está inactiva.',
      errorServer: 'El servicio de analíticas no está disponible temporalmente.',
      errorNetwork: 'Error de red al consultar el panel. Verifique su conexión.',
    },
    revenue: {
      title: 'Revenue & Performance Dashboard',
      subtitle: 'Analítica de retorno de inversión, inversión publicitaria en Meta y cohortes comerciales.',
      investment: 'Inversión Meta',
      attributedLeads: 'Prospectos Atribuidos',
      wonCount: 'Ventas Cerradas',
      totalCollected: 'Total Cobrado',
      blendedRoas: 'ROAS Blended',
      timeSeries: 'Serie Temporal de Rendimiento',
      funnel: 'Embudo de Conversión',
      funnelRegistered: 'Leads Registrados',
      funnelContacted: 'Contactados',
      funnelQualified: 'Calificados',
      funnelWon: 'Ganados (Ventas)',
      campaignsPerformance: 'Rendimiento por Campaña',
      campaignName: 'Nombre de Campaña',
      impressions: 'Impresiones',
      spend: 'Inversión',
      clicks: 'Clics',
      cpl: 'CPL Atrib.',
      salesCount: 'Ventas',
      revenue: 'Ingresos',
      roas: 'ROAS',
      noData: 'No hay datos financieros para el período seleccionado.',
      currencyMode: 'Moneda Normalizada',
      granularity: 'Granularidad',
      daily: 'Diario',
      weekly: 'Semanal',
      monthly: 'Mensual',
      startDate: 'Inicio',
      endDate: 'Fin',
      vendedor: 'Vendedor',
      campana: 'Campaña Meta',
      allCampaigns: 'Todas las Campañas',
      allSalespeople: 'Todos los Vendedores',
      resetFilters: 'Restablecer',
      processingMetrics: 'Procesando métricas financieras...',
      directAttributed: 'Atribuible directa:',
      totalCrm: 'Total CRM:',
      cplAttributed: 'CPL Atrib.:',
      chartSpend: 'Inversión',
      chartRevenue: 'Ingresos',
      chartLeads: 'Leads (x10)',
      breakdownTitle: 'Desglose por Campañas y Conjuntos de Anuncios',
      thCampaignAdSet: 'Campaña / Ad Set',
      thSpend: 'Inversión',
      thClicks: 'Clicks',
      thLeadsCrm: 'Leads CRM',
      thCpl: 'CPL',
      thSales: 'Ventas',
      thCollections: 'Cobros',
      thRoas: 'ROAS',
      noCampaignData: 'Sin datos de campañas registrados para este rango.',
      clientRequired: 'Por favor, seleccione una empresa cliente para visualizar las métricas.',
      unauthorized: 'Sesión no válida o expirada. Por favor, vuelva a ingresar.',
      forbidden: 'No tienes autorización para acceder a los datos financieros de esta empresa.',
      notFound: 'Empresa no encontrada o inactiva.',
      serverError: 'El servicio de analíticas no está disponible temporalmente.',
      networkError: 'Error de conexión. Verifique su red.',
      exchangeRateWarning: 'Faltan tasas de cambio históricas (exchange_rates) para algunas fechas del rango seleccionado. Los consolidados normalizados pueden figurar incompletos o nulos. Configure las tasas correspondientes en la administración.',
    },
    admin: {
      title: 'Centro de Control Administrativo',
      subtitle: 'Gestión global de empresas, usuarios, divisas, y sincronización operativa multi-tenant.',
      newCompany: 'Nueva Empresa',
      authorizeUser: 'Autorizar Usuario',
      searchClients: 'Buscar empresa o slug...',
      searchUsers: 'Buscar usuario o correo...',
      loadingClients: 'Cargando empresas...',
      noResults: 'Sin Resultados',
      noClientsFound: 'No se encontraron empresas registradas.',
      noUsersFound: 'No se encontraron usuarios registrados.',
      tabs: {
        companies: 'Empresas',
        users: 'Usuarios & Invitaciones',
        assets: 'Activos Meta & Scopes',
        sync: 'Salud & Sync Meta',
        rates: 'Tasas de Cambio',
        audit: 'Logs de Auditoría',
      },
      companies: {
        title: 'Gestión de Empresas',
        create: 'Nueva Empresa',
        name: 'Nombre',
        slug: 'Slug',
        timezone: 'Zona Horaria',
        currency: 'Moneda por Defecto',
        actions: 'Acciones',
        status: 'Estado',
        edit: 'Editar',
        deactivate: 'Desactivar',
        reactivate: 'Reactivar',
        active: 'Activo',
        inactive: 'Inactivo',
      },
      users: {
        title: 'Usuarios & Invitaciones',
        invite: 'Invitar Usuario',
        email: 'Correo Electrónico',
        role: 'Rol Autorizado',
        sendInvite: 'Generar Enlace de Invitación',
        copyInvite: 'Copiar Enlace',
        status: 'Estado',
        suspend: 'Suspender',
        reactivate: 'Reactivar',
        pendingActivation: 'Pendiente de activación',
        active: 'Activo',
        suspended: 'Suspendido',
        invited: 'Invitado',
      },
      assets: {
        title: 'Activos Meta & Asignaciones',
        registerManual: 'Registrar Activo Manual',
        adAccounts: 'Cuentas Publicitarias',
        dataSources: 'Píxeles y Datasets',
        scopes: 'Asignaciones de Empresas',
        accountId: 'ID Cuenta',
        datasetId: 'ID Píxel/Dataset',
        company: 'Empresa',
        effectiveDates: 'Vigencia',
        status: 'Estado',
        noAssets: 'No hay activos registrados.',
      },
      sync: {
        title: 'Salud & Sincronización Meta',
        manualSync: 'Sincronización Manual',
        syncNow: 'Sincronizar Ahora',
        syncing: 'Sincronizando...',
        statusTitle: 'Estado de la Conexión',
        lastSync: 'Última Sincronización',
        historyTitle: 'Historial de Sincronizaciones',
        page: 'Página',
        of: 'de',
        prev: 'Anterior',
        next: 'Siguiente',
        noLogs: 'No hay registros de sincronización disponibles.',
      },
      rates: {
        title: 'Tasas de Cambio Históricas',
        create: 'Nueva Tasa',
        rate: 'Tasa (ARS/USD)',
        validFrom: 'Válido Desde',
        validTo: 'Válido Hasta',
        current: 'Actual',
        delete: 'Eliminar',
        noRates: 'No hay tasas de cambio registradas.',
      },
      audit: {
        title: 'Logs de Auditoría de Configuración',
        user: 'Usuario',
        action: 'Acción',
        resource: 'Recurso',
        date: 'Fecha',
        details: 'Detalles',
        noLogs: 'No hay logs de auditoría registrados.',
      },
    },
    leads: {
      title: 'Gestión de Leads & Pipeline Comercial',
      subtitle: 'Administración del ciclo comercial, captura de prospectos y control de cierres.',
      importCsv: 'Importar CSV',
      newLead: 'Nuevo Prospecto',
      searchPlaceholder: 'Buscar por nombre, email o teléfono...',
      allStages: 'Todas las Etapas',
      allSalespeople: 'Todos los Vendedores',
      activeOnly: 'Activos',
      archivedOnly: 'Archivados',
      kanban: 'Kanban',
      table: 'Tabla',
      loadingLeads: 'Cargando prospectos y pipeline...',
      noLeadsTitle: 'No se encontraron prospectos',
      noLeadsDesc: 'Comenzá dando de alta un nuevo lead de forma manual o importando un lote CSV.',
      createFirstLead: 'Crear Primer Prospecto',
      unassigned: 'Sin asignar',
      viewDetail: 'Ver Detalle',
      prevStage: 'Retroceder etapa',
      nextStage: 'Avanzar etapa',
      stages: {
        new: 'Nuevo',
        contacted: 'Contactado',
        qualified: 'Calificado',
        won: 'Ganado',
        lost: 'Perdido',
      },
      tableTh: {
        lead: 'Prospecto',
        contact: 'Contacto',
        stage: 'Etapa',
        salesperson: 'Vendedor',
        value: 'Valor Estimado',
        actions: 'Acciones',
      },
    },
    campaigns: {
      title: 'Campañas & Meta Ads',
      subtitle: 'Rendimiento publicitario oficial, atribución y métricas multimoneda.',
      manageAssets: 'Administrar Activos',
      syncNow: 'Sincronizar Meta',
      syncing: 'Sincronizando...',
      companyLabel: 'Empresa:',
      selectCompanyPlaceholder: 'Seleccione una empresa...',
      levelTabs: {
        summary: 'Resumen Blended',
        dataset: 'Por Píxel',
        campaign: 'Campañas',
        adset: 'AdSets',
      },
      currencyAll: 'Todas las divisas',
      currencyArs: 'ARS (Pesos)',
      currencyUsd: 'USD (Dólares)',
      from: 'Desde:',
      to: 'Hasta:',
      lastSync: 'Última sincronización:',
      noSyncRecorded: 'Sin sincronización registrada',
      loading: 'Cargando métricas de Meta Ads...',
      emptyTitle: 'Sin Métricas Publicitarias Sincronizadas',
      emptyDesc: 'No se encontraron registros de inversión para los filtros seleccionados. Ejecute una sincronización o asigne cuentas publicitarias.',
      tableTh: {
        entity: 'Campaña / Entidad',
        status: 'Estado',
        metaSpend: 'Inversión (Meta)',
        metaClicks: 'Clics (Meta)',
        metaLeads: 'Leads (Meta)',
        metaCpl: 'CPL (Meta)',
        crmLeads: 'Leads (CRM)',
        crmCpl: 'CPL (CRM)',
        crmSales: 'Ventas (CRM)',
        crmCollected: 'Cobrado (CRM)',
        roasCollected: 'ROAS Cobrado',
      },
      badgeBlended: 'Blended',
      badgeMixedCampaign: 'Campaña Mixta Aislada',
      badgeCurrency: 'Moneda:',
      noAttribution: 'Sin atribución',
    },
    settings: {
      title: 'Configuración de Perfil',
      subtitle: 'Gestión de perfil, identidad y seguridad de acceso a Anima MKT CRM.',
      language: 'Preferencia de Idioma',
      selectLanguage: 'Seleccionar Idioma',
      password: 'Seguridad y Contraseña',
      identityRoleTitle: 'Perfil de Identidad & Rol',
      emailLabel: 'Correo Electrónico:',
      roleLabel: 'Rol en MongoDB:',
      accessSecurityTitle: 'Seguridad de Acceso & Proveedores Vinculados',
      accessSecurityDesc: 'Administrá los métodos de autenticación habilitados para ingresar a tu cuenta.',
      googleProvider: 'Google Workspace / Gmail',
      googleConnected: 'Conectado',
      googleNotConnected: 'No conectado',
      googleLinkedTo: 'Vinculado al correo {email}.',
      googleNotAvailable: 'No disponible como método de inicio directo.',
      passwordProvider: 'Contraseña Directa',
      passwordConfigured: 'Configurada',
      passwordNotConfigured: 'No configurada',
      passwordActiveDesc: 'Permite iniciar sesión ingresando correo y contraseña en el CRM.',
      passwordInactiveDesc: 'Tu cuenta fue creada con Google. Podés configurar una contraseña para habilitar acceso directo.',
      forgotOrChange: '¿Olvidaste o querés cambiarla?',
      resetViaEmail: 'Restablecer vía Email',
      resetEmailSent: 'Correo enviado',
      enablePasswordTitle: '¿Deseas habilitar acceso con correo y contraseña?',
      enablePasswordDesc: 'Te permitirá ingresar directamente sin depender del popup de Google. Tu cuenta y permisos permanecerán idénticos.',
      createPassword: 'Crear Contraseña',
      configurePasswordTitle: 'Configurar Contraseña de Acceso',
      cancelAction: 'Cancelar',
      newPassword: 'Nueva Contraseña',
      newPasswordPlaceholder: 'Mínimo 6 caracteres',
      confirmPassword: 'Confirmar Contraseña',
      confirmPasswordPlaceholder: 'Repetí la contraseña',
      minChars: 'Al menos 6 caracteres',
      passwordsMatch: 'Las contraseñas coinciden',
      passwordsDontMatch: 'Las contraseñas no coinciden',
      linking: 'Vinculando...',
      setPassword: 'Establecer Contraseña',
      passwordsMismatchError: 'Las contraseñas ingresadas no coinciden.',
    },
    socialAnalyzer: {
      title: 'Analizador de Clientes & Redes Sociales',
      subtitle: 'Diagnóstico inteligente de presencia, cadencia, engagement y estrategia accionable potenciado por IA.',
      companyLabel: 'Empresa:',
      selectCompanyPlaceholder: 'Seleccionar empresa...',
      connectProfile: 'Vincular Perfil Social',
      importData: 'Cargar Publicaciones (CSV/JSON)',
      runAiDiagnostic: 'Ejecutar Diagnóstico IA',
      runningAi: 'Analizando con IA...',
      reRunAiDiagnostic: 'Regenerar Diagnóstico con IA',
      exportReport: 'Exportar Informe',
      disconnect: 'Desconectar Perfil',
      confirmDisconnect: '¿Confirmas desconectar este perfil y purgar sus datos históricos?',
      noProfileTitle: 'Sin Perfil Social Conectado',
      noProfileDesc: 'Conectá la cuenta de Instagram o Facebook de la empresa o cargá publicaciones manualmente para generar el diagnóstico.',
      noSnapshotTitle: 'Sin Publicaciones Registradas',
      noSnapshotDesc: 'Este perfil no cuenta con publicaciones cargadas aún. Subí un archivo CSV/JSON o conectá la API oficial para comenzar.',
      uploadPosts: 'Subir Publicaciones',
      profileCard: {
        followers: 'Seguidores',
        following: 'Seguidos',
        posts: 'Publicaciones',
        status: 'Estado',
        lastUpdated: 'Última actualización',
        sourceApi: 'Meta Graph API',
        sourceManual: 'Carga Manual',
      },
      kpis: {
        analyzedPosts: 'Posts Auditados',
        cadencePerWeek: 'Frecuencia Semanal',
        postsPerMonth: 'Posts / Mes',
        avgDaysBetween: 'Días entre Publicaciones',
        consistencyScore: 'Índice de Consistencia',
        engagementRate: 'Tasa de Engagement Real',
        erOverReach: 'sobre Alcance',
        erOverFollowers: 'sobre Seguidores (Proxy)',
        totalInteractions: 'Interacciones Totales',
        totalSaves: 'Guardados Totales',
        formatBreakdown: 'Distribución por Formato',
      },
      pillars: {
        presence: 'Presencia & Perfil',
        contentQuality: 'Calidad de Contenido',
        cadenceAndConsistency: 'Cadencia & Constancia',
        engagement: 'Engagement & Comunidad',
        growthOpportunities: 'Oportunidades de Crecimiento',
        scoreLabel: 'Puntuación General',
      },
      findingsTitle: 'Hallazgos Estratégicos Basados en Evidencia',
      evidenceLabel: 'Evidencia:',
      actionPlanTitle: 'Plan de Acción Estratégico (30 Días)',
      tableTh: {
        phase: 'Fase / Timing',
        action: 'Acción Táctica',
        format: 'Formato',
        objective: 'Objetivo',
        impact: 'Impacto Esperado',
      },
      risksTitle: 'Limitaciones y Consideraciones Técnicas',
      bestContent: 'Mejores Publicaciones por Interacción',
      worstContent: 'Publicaciones de Menor Tracción',
      interactions: 'interacciones',
      saves: 'guardados',
      modalConnect: {
        title: 'Vincular Perfil Social Comercial',
        platform: 'Plataforma',
        username: 'Nombre de Usuario (ej: animamkt)',
        accountName: 'Nombre Público de la Cuenta',
        biography: 'Biografía del Perfil',
        website: 'Sitio Web / Link en Bio',
        followers: 'Cantidad de Seguidores',
        follows: 'Cuentas Seguidas',
        save: 'Guardar Perfil',
      },
      modalUpload: {
        title: 'Cargar Lote de Publicaciones (CSV o JSON)',
        desc: 'Podés subir un archivo CSV con las columnas: date, caption, format, likes, comments, shares, saves, reach, impressions.',
        pasteOrUpload: 'Pegar JSON o seleccionar archivo CSV',
        jsonPlaceholder: '[\n  {\n    "timestamp": "2026-08-20T14:00:00Z",\n    "format": "reel",\n    "caption": "Tu caption...",\n    "likes": 120,\n    "comments": 15,\n    "saves": 35,\n    "reach": 2500\n  }\n]',
        downloadTemplate: 'Descargar Plantilla CSV',
        processUpload: 'Procesar e Ingestar Publicaciones',
      }
    },
    googleIntelligence: {
      title: 'Google Intelligence & SEO Local',
      subtitle: 'Visibilidad orgánica, ficha de Google Business Profile, reseñas y radar competitivo local.',
      companyLabel: 'Empresa:',
      connectEntity: 'Vincular Google',
      importData: 'Importar Datos (CSV/JSON)',
      addCompetitor: 'Añadir Competidor',
      runAiDiagnostic: 'Generar Diagnóstico IA',
      reRunAiDiagnostic: 'Re-calcular Diagnóstico IA',
      runningAi: 'Analizando con IA...',
      noEntityTitle: 'Sin Perfil de Google Conectado',
      noEntityDesc: 'Vinculá la ficha de Google Business Profile, Search Console o cargá reseñas para comenzar.',
      tabs: {
        overview: 'Visión General',
        reputation: 'Ficha & Reseñas',
        seo: 'SEO & Search Console',
        trafficAndAds: 'Tráfico & Ads',
        competitors: 'Radar Competitivo',
        aiStrategy: 'Diagnóstico IA',
      },
      overview: {
        scoreTitle: 'Salud de Presencia en Google',
        scoreSubtitle: 'Índice ponderado de reputación, SEO y competitividad local.',
        gbpCard: 'Google Business Profile',
        gscCard: 'Search Console',
        ga4Card: 'Google Analytics 4',
        adsCard: 'Google Ads',
        connected: 'Conectado',
        disconnected: 'Sin Conectar',
        reviewsCount: 'Reseñas Verificadas',
        avgRating: 'Calificación Promedio',
        orgClicks: 'Clics Orgánicos',
        orgImpressions: 'Impresiones Orgánicas',
      },
      reputation: {
        title: 'Reputación & Reseñas de Clientes',
        subtitle: 'Monitoreo de satisfacción, tiempos de respuesta y redacción asistida de respuestas.',
        avgRating: 'Rating Promedio',
        totalReviews: 'Total Reseñas',
        responseRate: 'Tasa de Respuesta',
        avgResponseTime: 'Tiempo Medio de Respuesta',
        hours: 'hs',
        filterAll: 'Todas',
        filterUnanswered: 'Sin Responder',
        filter5Stars: '5 Estrellas',
        filterNegative: 'Críticas (1-3★)',
        draftAiReply: 'Sugerir Respuesta con IA (Borrador)',
        officialReply: 'Respuesta Oficial:',
        saveReply: 'Guardar Respuesta',
        generatingDraft: 'Redactando borrador con IA...',
        copyDraft: 'Copiar Borrador',
        repliedBadge: 'Respondida',
        unansweredBadge: 'Pendiente',
      },
      seo: {
        title: 'Rendimiento en Google Search Console',
        subtitle: 'Consultas orgánicas, CTR y páginas con mayor tracción en el buscador.',
        topQueriesTitle: 'Top Consultas de Búsqueda',
        queryCol: 'Consulta',
        clicksCol: 'Clics',
        impressionsCol: 'Impresiones',
        ctrCol: 'CTR',
        positionCol: 'Posición Media',
        opportunitiesTitle: 'Oportunidades de Alto Alcance y Bajo CTR',
        opportunitiesDesc: 'Palabras clave con altas impresiones pero bajo porcentaje de clics (optimizar Title / Meta Description).',
      },
      trafficAndAds: {
        title: 'Tráfico Web y Campañas Pagas',
        subtitle: 'Métricas aisladas por canal con estricta separación de atribución.',
        organicTrafficBadge: 'Tráfico Orgánico en Sitio (GA4)',
        paidTrafficBadge: 'Inversión Paga en Buscador (Google Ads)',
        attributionWarning: 'Aviso de Atribución: Las métricas de GA4 reflejan sesiones en la web, mientras que Search Console y Google Ads miden interacciones en la página de resultados de Google. No deben sumarse directamente.',
      },
      competitors: {
        title: 'Radar Competitivo Local',
        subtitle: 'Benchmarking objetivo de presencia, reputación y volumen frente a competidores directos.',
        yourBusiness: 'Tu Empresa',
        competitorCol: 'Competidor / Negocio',
        categoryCol: 'Categoría',
        ratingCol: 'Rating',
        reviewsCol: 'Reseñas',
        gapCol: 'Diferencial',
        statusCol: 'Estado',
        leaderboardTitle: 'Ranking de Posicionamiento Local',
      },
      aiStrategy: {
        title: 'Diagnóstico Estratégico & Plan de Acción (IA)',
        overallScore: 'Puntuación Estratégica Integral',
        executiveSummary: 'Resumen Ejecutivo',
        pillarsTitle: 'Evaluación por Pilares Estratégicos',
        findingsTitle: 'Hallazgos Clave Priorizados',
        quickWinsTitle: 'Acciones Rápidas (Quick Wins)',
        roadmapTitle: 'Hoja de Ruta Táctica (30 / 60 / 90 Días)',
        masterPromptTitle: 'Prompt Maestro para Estrategia SEO/SEM (Anima MKT)',
        masterPromptDesc: 'Copiá y pegá este bloque estructurado en tu asistente de IA antes de analizar las métricas de cualquier cuenta y sincronizá las acciones comerciales con Kommo CRM.',
        copyMasterPrompt: 'Copiar Prompt Maestro SEO/SEM',
        masterPromptCopied: '¡Prompt Maestro copiado al portapapeles!',
        prospectPromptTitle: 'Radiografía de Lead & Closer de Ventas (Auditoría Comercial)',
        prospectPromptDesc: 'Analizá al prospecto con solo sus datos públicos de Google Places para clasificar el esfuerzo técnico, detectar puntos ciegos y obtener el guion de cierre para WhatsApp o reuniones.',
        copyProspectPrompt: 'Copiar Radiografía de Lead',
        prospectPromptCopied: '¡Radiografía de Lead copiada al portapapeles!',
        prospectBadge: 'Modo Prospección',
        disclaimer: 'Diferenciación estricta entre métricas verificadas y recomendaciones estratégicas. No se garantizan rankings ni ventas.',
      },
      modals: {
        connectTitle: 'Configurar / Vincular Google',
        prospectToggle: 'Modo Prospección (Sin acceso administrativo)',
        prospectToggleDesc: 'Auditar un cliente potencial usando únicamente sus datos públicos antes de formalizar el contrato.',
        businessName: 'Nombre del Negocio',
        websiteUrl: 'URL del Sitio Web',
        address: 'Dirección Comercial',
        city: 'Ciudad',
        category: 'Categoría Comercial',
        locationId: 'ID de Ficha Google Business Profile',
        siteUrl: 'URL en Search Console (ej: https://ejemplo.com)',
        ga4Property: 'ID de Propiedad GA4 (ej: 123456789)',
        adsCustomer: 'ID de Cliente Google Ads (ej: 123-456-7890)',
        importTitle: 'Importar Reseñas o Snapshots de Google',
        importDesc: 'Pegá un JSON estructurado o cargá un archivo CSV para ingestar reseñas o métricas históricas.',
        addCompetitorTitle: 'Registrar Competidor Local',
        compName: 'Nombre del Competidor',
        compCategory: 'Categoría',
        compCity: 'Ciudad',
        compRating: 'Calificación (1.0 a 5.0)',
        compReviews: 'Total de Reseñas',
        compWebsite: 'Sitio Web del Competidor',
      }
    }
  },
  en: {
    sidebar: {
      dashboard: 'Dashboard',
      revenue: 'ROI & Finance',
      leads: 'Leads & Pipeline',
      campaigns: 'Meta Campaigns',
      socialAnalyzer: 'Social Analyzer',
      googleIntelligence: 'Google Intelligence',
      admin: 'Administration',
      settings: 'Settings',
      logout: 'Log Out',
      brandTitle: 'ANIMA MKT CRM',
      brandSubtitle: 'Revenue Intelligence',
      closeMenu: 'Close menu',
      mainNavigation: 'Main navigation',
    },
    header: {
      systemOperating: 'System Operating',
      secureSession: 'Secure Session',
      logout: 'Log Out',
      openMenu: 'Open navigation menu',
      logoutTitle: 'Log out from Anima MKT CRM',
    },
    roles: {
      super_admin: 'SUPER ADMIN',
      admin: 'ADMIN',
      client: 'CLIENT',
      salesperson: 'SALESPERSON',
      media_buyer: 'MEDIA BUYER',
      user: 'USER',
    },
    common: {
      actions: 'Actions',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      add: 'Add',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      suspended: 'Suspended',
      invited: 'Invited',
      search: 'Search...',
      all: 'All',
      retry: 'Retry',
      loading: 'Loading...',
      error: 'An error occurred',
      success: 'Success',
      company: 'Company',
      selectCompany: 'Select a Company',
      allCompanies: 'All Companies',
      role: 'Role',
      date: 'Date',
      value: 'Value',
      none: 'None',
      back: 'Back',
      confirm: 'Confirm',
      warning: 'Warning',
      exportCsv: 'Export CSV',
      exportPdf: 'Export PDF',
      from: 'From:',
      to: 'To:',
      reset: 'Reset',
      allCurrencies: 'All currencies',
      allStages: 'All Stages',
      allSalespeople: 'All Salespeople',
      allCampaigns: 'All Campaigns',
      unassigned: 'Unassigned',
    },
    dashboard: {
      title: 'Performance & Commercial Dashboard',
      welcome: 'Welcome,',
      leadsCount: 'Total Leads',
      wonLeads: 'Closed Sales',
      conversionRate: 'Conversion Rate',
      totalCollected: 'Total Collected',
      recentLeads: 'Recent Leads',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      assignedTo: 'Assigned To',
      leadsInPipeline: 'Leads in Pipeline',
      won: 'Won:',
      convRate: 'Conv. Rate:',
      noData: 'No data',
      collectedRevenue: 'Collected Revenue',
      loadingCurrencies: 'Loading currencies...',
      errorLoadingCollections: 'Error loading collections',
      noCollections: 'No collections registered',
      metaInvestment: 'Meta Ads Investment',
      noMetaData: 'No Meta data',
      roasOnCollections: 'ROAS on Collections',
      roasCalculated: 'Calculated on collected revenue',
      roasRequires: 'Requires investment and revenue',
      pipelineDistribution: 'Pipeline Distribution',
      loadingDistribution: 'Loading distribution...',
      errorDistribution: 'Could not load the breakdown.',
      stageNew: '1. New',
      stageContacted: '2. Contacted',
      stageQualified: '3. Qualified',
      stageWon: '4. Won / Closed',
      stageLost: '5. Lost',
      salespersonPerformance: 'Salesperson Performance',
      loadingSalespeople: 'Loading salespeople...',
      errorSalespeople: 'Could not load salesperson performance.',
      noSalespeopleData: 'No salesperson data to show for this filter.',
      thSalesperson: 'Salesperson',
      thAssignedLeads: 'Assigned Leads',
      thWon: 'Won',
      thSales: 'Sales',
      thConvRate: 'Conv. Rate',
      thCollected: 'Collected',
      pendingActivation: 'Pending activation',
      openPipeline: 'Open Pipeline',
      openCampaigns: 'Open Campaigns',
      pipelineAndAssignments: 'Pipeline & Assignments',
      pipelineDesc: 'Kanban board with 5 commercial stages, controlled reassignment and bulk CSV import.',
      salesAndCollections: 'Sales & Collections in Cents',
      salesDesc: 'Control of partial and total collected amounts by currency with limit validation.',
      nextStep: 'Next Step: Stage 4',
      errorUnauthorized: 'Invalid or expired session. Please log in again.',
      errorForbidden: 'You do not have permission to view this company\'s statistics.',
      errorNotFound: 'The selected company does not exist or is inactive.',
      errorServer: 'The analytics service is temporarily unavailable.',
      errorNetwork: 'Network error querying the dashboard. Check your connection.',
    },
    revenue: {
      title: 'Revenue & Performance Dashboard',
      subtitle: 'Return on investment analytics, Meta Ads spend, and commercial cohorts.',
      investment: 'Meta Spend',
      attributedLeads: 'Attributed Leads',
      wonCount: 'Closed Sales',
      totalCollected: 'Total Collected',
      blendedRoas: 'Blended ROAS',
      timeSeries: 'Performance Time Series',
      funnel: 'Conversion Funnel',
      funnelRegistered: 'Registered Leads',
      funnelContacted: 'Contacted',
      funnelQualified: 'Qualified',
      funnelWon: 'Won (Sales)',
      campaignsPerformance: 'Performance by Campaign',
      campaignName: 'Campaign Name',
      impressions: 'Impressions',
      spend: 'Spend',
      clicks: 'Clicks',
      cpl: 'Attrib. CPL',
      salesCount: 'Sales',
      revenue: 'Revenue',
      roas: 'ROAS',
      noData: 'No financial data for the selected period.',
      currencyMode: 'Normalized Currency',
      granularity: 'Granularity',
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      startDate: 'Start Date',
      endDate: 'End Date',
      vendedor: 'Salesperson',
      campana: 'Meta Campaign',
      allCampaigns: 'All Campaigns',
      allSalespeople: 'All Salespeople',
      resetFilters: 'Reset',
      processingMetrics: 'Processing financial metrics...',
      directAttributed: 'Direct Attributed:',
      totalCrm: 'Total CRM:',
      cplAttributed: 'Attrib. CPL:',
      chartSpend: 'Spend',
      chartRevenue: 'Revenue',
      chartLeads: 'Leads (x10)',
      breakdownTitle: 'Breakdown by Campaigns and Ad Sets',
      thCampaignAdSet: 'Campaign / Ad Set',
      thSpend: 'Spend',
      thClicks: 'Clicks',
      thLeadsCrm: 'CRM Leads',
      thCpl: 'CPL',
      thSales: 'Sales',
      thCollections: 'Collections',
      thRoas: 'ROAS',
      noCampaignData: 'No campaign data recorded for this range.',
      clientRequired: 'Please select a client company to view financial metrics.',
      unauthorized: 'Invalid or expired session. Please log in again.',
      forbidden: 'You do not have permission to access financial data for this company.',
      notFound: 'Company not found or inactive.',
      serverError: 'Analytics service is temporarily unavailable.',
      networkError: 'Network error. Please verify your connection.',
      exchangeRateWarning: 'Historical exchange rates (exchange_rates) are missing for some dates in the selected range. Normalized totals may be incomplete or null. Configure the corresponding rates in Administration.',
    },
    admin: {
      title: 'Administrative Control Center',
      subtitle: 'Global management of companies, users, currencies, and multi-tenant operational synchronization.',
      newCompany: 'New Company',
      authorizeUser: 'Authorize User',
      searchClients: 'Search company or slug...',
      searchUsers: 'Search user or email...',
      loadingClients: 'Loading companies...',
      noResults: 'No Results',
      noClientsFound: 'No registered companies found.',
      noUsersFound: 'No registered users found.',
      tabs: {
        companies: 'Companies',
        users: 'Users & Invites',
        assets: 'Meta Assets & Scopes',
        sync: 'Meta Health & Sync',
        rates: 'Exchange Rates',
        audit: 'Audit Logs',
      },
      companies: {
        title: 'Manage Companies',
        create: 'New Company',
        name: 'Name',
        slug: 'Slug',
        timezone: 'Timezone',
        currency: 'Default Currency',
        actions: 'Actions',
        status: 'Status',
        edit: 'Edit',
        deactivate: 'Deactivate',
        reactivate: 'Reactivate',
        active: 'Active',
        inactive: 'Inactive',
      },
      users: {
        title: 'Users & Invites',
        invite: 'Invite User',
        email: 'Email Address',
        role: 'Authorized Role',
        sendInvite: 'Generate Invite Link',
        copyInvite: 'Copy Link',
        status: 'Status',
        suspend: 'Suspend',
        reactivate: 'Reactivate',
        pendingActivation: 'Pending activation',
        active: 'Active',
        suspended: 'Suspended',
        invited: 'Invited',
      },
      assets: {
        title: 'Meta Assets & Scopes',
        registerManual: 'Register Manual Asset',
        adAccounts: 'Ad Accounts',
        dataSources: 'Pixels and Datasets',
        scopes: 'Company Scopes',
        accountId: 'Account ID',
        datasetId: 'Pixel/Dataset ID',
        company: 'Company',
        effectiveDates: 'Effective Dates',
        status: 'Status',
        noAssets: 'No assets registered.',
      },
      sync: {
        title: 'Meta Health & Synchronization',
        manualSync: 'Manual Synchronization',
        syncNow: 'Sync Now',
        syncing: 'Syncing...',
        statusTitle: 'Connection Status',
        lastSync: 'Last Synced',
        historyTitle: 'Sync History',
        page: 'Page',
        of: 'of',
        prev: 'Previous',
        next: 'Next',
        noLogs: 'No sync logs available.',
      },
      rates: {
        title: 'Historical Exchange Rates',
        create: 'New Rate',
        rate: 'Rate (ARS/USD)',
        validFrom: 'Valid From',
        validTo: 'Valid To',
        current: 'Current',
        delete: 'Delete',
        noRates: 'No exchange rates registered.',
      },
      audit: {
        title: 'Configuration Audit Logs',
        user: 'User',
        action: 'Action',
        resource: 'Resource',
        date: 'Date',
        details: 'Details',
        noLogs: 'No audit logs recorded.',
      },
    },
    leads: {
      title: 'Lead & Commercial Pipeline Management',
      subtitle: 'Commercial cycle administration, prospect capture, and sales closing control.',
      importCsv: 'Import CSV',
      newLead: 'New Prospect',
      searchPlaceholder: 'Search by name, email or phone...',
      allStages: 'All Stages',
      allSalespeople: 'All Salespeople',
      activeOnly: 'Active',
      archivedOnly: 'Archived',
      kanban: 'Kanban',
      table: 'Table',
      loadingLeads: 'Loading prospects and pipeline...',
      noLeadsTitle: 'No prospects found',
      noLeadsDesc: 'Start by creating a new lead manually or importing a CSV batch.',
      createFirstLead: 'Create First Lead',
      unassigned: 'Unassigned',
      viewDetail: 'View Detail',
      prevStage: 'Previous stage',
      nextStage: 'Next stage',
      stages: {
        new: 'NEW',
        contacted: 'CONTACTED',
        qualified: 'QUALIFIED',
        won: 'WON',
        lost: 'LOST',
      },
      tableTh: {
        lead: 'Lead',
        contact: 'Contact',
        stage: 'Stage',
        salesperson: 'Salesperson',
        value: 'Estimated Value',
        actions: 'Actions',
      },
    },
    campaigns: {
      title: 'Campaigns & Meta Ads',
      subtitle: 'Official advertising performance, attribution and multi-currency metrics.',
      manageAssets: 'Manage Assets',
      syncNow: 'Sync Meta',
      syncing: 'Syncing...',
      companyLabel: 'Company:',
      selectCompanyPlaceholder: 'Select a company...',
      levelTabs: {
        summary: 'Blended Summary',
        dataset: 'By Pixel',
        campaign: 'Campaigns',
        adset: 'AdSets',
      },
      currencyAll: 'All currencies',
      currencyArs: 'ARS (Pesos)',
      currencyUsd: 'USD (Dollars)',
      from: 'From:',
      to: 'To:',
      lastSync: 'Last synced:',
      noSyncRecorded: 'No sync recorded',
      loading: 'Loading Meta Ads metrics...',
      emptyTitle: 'No Ad Metrics Synced',
      emptyDesc: 'No ad spend records found for selected filters. Run a sync or assign ad accounts.',
      tableTh: {
        entity: 'Campaign / Entity',
        status: 'Status',
        metaSpend: 'Spend (Meta)',
        metaClicks: 'Clicks (Meta)',
        metaLeads: 'Leads (Meta)',
        metaCpl: 'CPL (Meta)',
        crmLeads: 'Leads (CRM)',
        crmCpl: 'CPL (CRM)',
        crmSales: 'Sales (CRM)',
        crmCollected: 'Collected (CRM)',
        roasCollected: 'Collected ROAS',
      },
      badgeBlended: 'Blended',
      badgeMixedCampaign: 'Isolated Mixed Campaign',
      badgeCurrency: 'Currency:',
      noAttribution: 'No attribution',
    },
    settings: {
      title: 'Profile Settings',
      subtitle: 'Profile management, identity and access security for Anima MKT CRM.',
      language: 'Language Preference',
      selectLanguage: 'Select Language',
      password: 'Security & Password',
      identityRoleTitle: 'Identity Profile & Role',
      emailLabel: 'Email Address:',
      roleLabel: 'MongoDB Role:',
      accessSecurityTitle: 'Access Security & Linked Providers',
      accessSecurityDesc: 'Manage the authentication methods enabled to log into your account.',
      googleProvider: 'Google Workspace / Gmail',
      googleConnected: 'Connected',
      googleNotConnected: 'Not connected',
      googleLinkedTo: 'Linked to {email}.',
      googleNotAvailable: 'Not available as a direct sign-in method.',
      passwordProvider: 'Direct Password',
      passwordConfigured: 'Configured',
      passwordNotConfigured: 'Not configured',
      passwordActiveDesc: 'Allows sign-in via email and password in the CRM.',
      passwordInactiveDesc: 'Your account was created with Google. You can set a password to enable direct access.',
      forgotOrChange: 'Forgot or want to change it?',
      resetViaEmail: 'Reset via Email',
      resetEmailSent: 'Email sent',
      enablePasswordTitle: 'Enable email and password access?',
      enablePasswordDesc: 'This will let you sign in directly without depending on Google popup. Your account and permissions will remain identical.',
      createPassword: 'Create Password',
      configurePasswordTitle: 'Configure Access Password',
      cancelAction: 'Cancel',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Minimum 6 characters',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Repeat the password',
      minChars: 'At least 6 characters',
      passwordsMatch: 'Passwords match',
      passwordsDontMatch: 'Passwords do not match',
      linking: 'Linking...',
      setPassword: 'Set Password',
      passwordsMismatchError: 'The entered passwords do not match.',
    },
    socialAnalyzer: {
      title: 'Social Client & Media Analyzer',
      subtitle: 'Intelligent AI-powered diagnostic of presence, cadence, engagement, and actionable strategy.',
      companyLabel: 'Company:',
      selectCompanyPlaceholder: 'Select company...',
      connectProfile: 'Link Social Profile',
      importData: 'Import Posts (CSV/JSON)',
      runAiDiagnostic: 'Run AI Diagnostic',
      runningAi: 'Analyzing with AI...',
      reRunAiDiagnostic: 'Regenerate AI Diagnostic',
      exportReport: 'Export Report',
      disconnect: 'Disconnect Profile',
      confirmDisconnect: 'Are you sure you want to disconnect this profile and purge its historical data?',
      noProfileTitle: 'No Social Profile Connected',
      noProfileDesc: 'Link the company Instagram or Facebook account or upload posts manually to generate the diagnostic.',
      noSnapshotTitle: 'No Posts Recorded',
      noSnapshotDesc: 'This profile has no uploaded posts yet. Upload a CSV/JSON file or connect the official API to start.',
      uploadPosts: 'Upload Posts',
      profileCard: {
        followers: 'Followers',
        following: 'Following',
        posts: 'Posts',
        status: 'Status',
        lastUpdated: 'Last updated',
        sourceApi: 'Meta Graph API',
        sourceManual: 'Manual Upload',
      },
      kpis: {
        analyzedPosts: 'Audited Posts',
        cadencePerWeek: 'Weekly Frequency',
        postsPerMonth: 'Posts / Month',
        avgDaysBetween: 'Days Between Posts',
        consistencyScore: 'Consistency Index',
        engagementRate: 'Real Engagement Rate',
        erOverReach: 'over Reach',
        erOverFollowers: 'over Followers (Proxy)',
        totalInteractions: 'Total Interactions',
        totalSaves: 'Total Saves',
        formatBreakdown: 'Format Distribution',
      },
      pillars: {
        presence: 'Presence & Profile',
        contentQuality: 'Content Quality',
        cadenceAndConsistency: 'Cadence & Consistency',
        engagement: 'Engagement & Community',
        growthOpportunities: 'Growth Opportunities',
        scoreLabel: 'Overall Score',
      },
      findingsTitle: 'Evidence-Backed Strategic Findings',
      evidenceLabel: 'Evidence:',
      actionPlanTitle: '30-Day Strategic Action Plan',
      tableTh: {
        phase: 'Phase / Timing',
        action: 'Tactical Action',
        format: 'Format',
        objective: 'Objective',
        impact: 'Expected Impact',
      },
      risksTitle: 'Limitations & Technical Considerations',
      bestContent: 'Top Posts by Interaction',
      worstContent: 'Lowest Traction Posts',
      interactions: 'interactions',
      saves: 'saves',
      modalConnect: {
        title: 'Link Commercial Social Profile',
        platform: 'Platform',
        username: 'Username (e.g. animamkt)',
        accountName: 'Public Account Name',
        biography: 'Profile Biography',
        website: 'Website / Link in Bio',
        followers: 'Followers Count',
        follows: 'Following Count',
        save: 'Save Profile',
      },
      modalUpload: {
        title: 'Upload Posts Batch (CSV or JSON)',
        desc: 'You can upload a CSV file with columns: date, caption, format, likes, comments, shares, saves, reach, impressions.',
        pasteOrUpload: 'Paste JSON or select CSV file',
        jsonPlaceholder: '[\n  {\n    "timestamp": "2026-08-20T14:00:00Z",\n    "format": "reel",\n    "caption": "Your caption...",\n    "likes": 120,\n    "comments": 15,\n    "saves": 35,\n    "reach": 2500\n  }\n]',
        downloadTemplate: 'Download CSV Template',
        processUpload: 'Process and Ingest Posts',
      }
    },
    googleIntelligence: {
      title: 'Google Intelligence & Local SEO',
      subtitle: 'Organic search visibility, Google Business Profile presence, reviews and local competitive radar.',
      companyLabel: 'Company:',
      connectEntity: 'Connect Google',
      importData: 'Import Data (CSV/JSON)',
      addCompetitor: 'Add Competitor',
      runAiDiagnostic: 'Run AI Diagnostic',
      reRunAiDiagnostic: 'Re-run AI Diagnostic',
      runningAi: 'Analyzing with AI...',
      noEntityTitle: 'No Google Entity Connected',
      noEntityDesc: 'Connect Google Business Profile, Search Console or import customer reviews to begin.',
      tabs: {
        overview: 'Overview',
        reputation: 'Profile & Reviews',
        seo: 'SEO & Search Console',
        trafficAndAds: 'Traffic & Ads',
        competitors: 'Competitive Radar',
        aiStrategy: 'AI Diagnostic',
      },
      overview: {
        scoreTitle: 'Google Presence Health Score',
        scoreSubtitle: 'Weighted composite index of reputation, organic SEO and local competitiveness.',
        gbpCard: 'Google Business Profile',
        gscCard: 'Search Console',
        ga4Card: 'Google Analytics 4',
        adsCard: 'Google Ads',
        connected: 'Connected',
        disconnected: 'Disconnected',
        reviewsCount: 'Verified Reviews',
        avgRating: 'Average Rating',
        orgClicks: 'Organic Clicks',
        orgImpressions: 'Organic Impressions',
      },
      reputation: {
        title: 'Reputation & Customer Reviews',
        subtitle: 'Customer satisfaction monitoring, response times and assisted AI review reply drafting.',
        avgRating: 'Average Rating',
        totalReviews: 'Total Reviews',
        responseRate: 'Response Rate',
        avgResponseTime: 'Average Response Time',
        hours: 'hrs',
        filterAll: 'All',
        filterUnanswered: 'Unanswered',
        filter5Stars: '5 Stars',
        filterNegative: 'Critical (1-3★)',
        draftAiReply: 'Draft AI Reply (Draft Only)',
        officialReply: 'Official Reply:',
        saveReply: 'Save Reply',
        generatingDraft: 'Drafting reply with AI...',
        copyDraft: 'Copy Draft',
        repliedBadge: 'Replied',
        unansweredBadge: 'Pending',
      },
      seo: {
        title: 'Google Search Console Performance',
        subtitle: 'Organic search queries, click-through rates and high-traffic landing pages.',
        topQueriesTitle: 'Top Search Queries',
        queryCol: 'Query',
        clicksCol: 'Clicks',
        impressionsCol: 'Impressions',
        ctrCol: 'CTR',
        positionCol: 'Average Position',
        opportunitiesTitle: 'High Reach, Low CTR Opportunities',
        opportunitiesDesc: 'Keywords with significant impression volume but low click-through rates (optimize Title / Meta Description).',
      },
      trafficAndAds: {
        title: 'Website Traffic & Paid Campaigns',
        subtitle: 'Channel-isolated metrics with strict attribution separation.',
        organicTrafficBadge: 'On-Site Organic Traffic (GA4)',
        paidTrafficBadge: 'Paid Search Investment (Google Ads)',
        attributionWarning: 'Attribution Notice: GA4 metrics reflect on-site web sessions, while Search Console and Google Ads measure Search Engine Results Page (SERP) interactions. They must not be directly aggregated.',
      },
      competitors: {
        title: 'Local Competitive Radar',
        subtitle: 'Objective benchmarking of presence, reputation and volume against direct local competitors.',
        yourBusiness: 'Your Business',
        competitorCol: 'Competitor / Business',
        categoryCol: 'Category',
        ratingCol: 'Rating',
        reviewsCol: 'Reviews',
        gapCol: 'Differential',
        statusCol: 'Status',
        leaderboardTitle: 'Local Market Leaderboard',
      },
      aiStrategy: {
        title: 'Strategic AI Diagnostic & Action Plan',
        overallScore: 'Comprehensive Strategic Score',
        executiveSummary: 'Executive Summary',
        pillarsTitle: 'Strategic Pillars Assessment',
        findingsTitle: 'Prioritized Key Findings',
        quickWinsTitle: 'Quick Wins',
        roadmapTitle: 'Tactical Roadmap (30 / 60 / 90 Days)',
        masterPromptTitle: 'Master SEO/SEM Strategic Prompt (Anima MKT)',
        masterPromptDesc: 'Copy and paste this structured framework into your AI assistant before analyzing any client metrics, and sync commercial actions directly to Kommo CRM.',
        copyMasterPrompt: 'Copy Master SEO/SEM Prompt',
        masterPromptCopied: 'Master Prompt copied to clipboard!',
        prospectPromptTitle: 'Lead Radiography & Sales Closer (Commercial Audit)',
        prospectPromptDesc: 'Analyze a prospect using only public Google Places data to assess technical effort, pinpoint blind spots, and generate closing scripts for WhatsApp or sales meetings.',
        copyProspectPrompt: 'Copy Lead Radiography',
        prospectPromptCopied: 'Lead Radiography copied to clipboard!',
        prospectBadge: 'Prospecting Mode',
        disclaimer: 'Strict separation between measured metrics and strategic recommendations. No ranking or sales guarantees.',
      },
      modals: {
        connectTitle: 'Configure / Connect Google',
        prospectToggle: 'Prospecting Mode (No admin credentials)',
        prospectToggleDesc: 'Audit and evaluate a potential client using only public data before signing a contract.',
        businessName: 'Business Name',
        websiteUrl: 'Website URL',
        address: 'Business Address',
        city: 'City',
        category: 'Business Category',
        locationId: 'Google Business Profile Location ID',
        siteUrl: 'Search Console Site URL (e.g. https://example.com)',
        ga4Property: 'GA4 Property ID (e.g. 123456789)',
        adsCustomer: 'Google Ads Customer ID (e.g. 123-456-7890)',
        importTitle: 'Import Google Reviews or Snapshots',
        importDesc: 'Paste structured JSON or upload a CSV file to ingest historical reviews or metrics.',
        addCompetitorTitle: 'Register Local Competitor',
        compName: 'Competitor Name',
        compCategory: 'Category',
        compCity: 'City',
        compRating: 'Rating (1.0 to 5.0)',
        compReviews: 'Total Reviews',
        compWebsite: 'Competitor Website',
      }
    }
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'es';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (keyPath, variables = {}) => {
    const keys = keyPath.split('.');
    let value = translations[language];
    for (const key of keys) {
      if (value && value[key] !== undefined) {
        value = value[key];
      } else {
        // Fallback to Spanish dictionary
        let fallbackVal = translations.es;
        for (const fk of keys) {
          if (fallbackVal && fallbackVal[fk] !== undefined) {
            fallbackVal = fallbackVal[fk];
          } else {
            fallbackVal = null;
            break;
          }
        }
        return fallbackVal || keyPath;
      }
    }

    if (typeof value === 'string') {
      let str = value;
      Object.entries(variables).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
      return str;
    }

    return keyPath;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fail-safe fallback for unit tests running outside a LanguageProvider
    return {
      language: 'es',
      setLanguage: () => {},
      t: (keyPath, variables = {}) => {
        const keys = keyPath.split('.');
        let value = translations.es;
        for (const k of keys) {
          if (value && value[k] !== undefined) {
            value = value[k];
          } else {
            return keyPath;
          }
        }
        if (typeof value === 'string') {
          let str = value;
          Object.entries(variables).forEach(([k, v]) => {
            str = str.replace(`{${k}}`, v);
          });
          return str;
        }
        return keyPath;
      }
    };
  }
  return context;
}
